
# output <variable_name> {
#   value = "<variable_value>"
#   <arguments>
# }


resource "local_file" "pet" {
  filename = var.filename
  content  = "My favorite pet is Mr.Cat"
}

resource "random_pet" "my-pet" {
  prefix    = var.prefix
  separator = var.separator
  length    = var.separator 
}


output pet-name {
  value = random_pet.my-pet.id
  description = "Record the value of pet ID generated by the random_pet resource"
}

# Output variables mostly used to print 
# on the screen the provishioned resources or
# to feed 3-rd party apps as inputs 
# (e.g. Ansible playbooks, Chef cookbooks, Scripts)

# After terraform apply
# we can use 
# 'terraform output'
# OR
# 'terraform output <output_variable_name>'
# to see all output variables 